name: cloudcb-server
type: web
instance_type: nano
regions:
  - was
ports:
  - port: 3000
    protocol: http
env:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3000"
routes:
  - path: /
    port: 3000
builder: buildpack
run_command: node apps/server/dist/index.js
